import preset from '../../../vendor/filament/filament/tailwind.config.preset'

import defaultTheme from 'tailwindcss/defaultTheme'

const scheduledConferenceBillingHookSafelist = [
    'mb-6',
    'mt-1',
    'mt-2',
    'mt-4',
    'mt-6',
    'inline-flex',
    'flex',
    'grid',
    'w-fit',
    'flex-col',
    'flex-wrap',
    'items-center',
    'justify-center',
    'gap-1',
    'gap-3',
    'gap-4',
    'gap-6',
    'space-y-2',
    'space-y-6',
    'rounded-full',
    'rounded-lg',
    'rounded-md',
    'rounded-xl',
    'border',
    'border-amber-200',
    'border-gray-200',
    'border-green-200',
    'border-indigo-200',
    'border-red-200',
    'bg-amber-50',
    'bg-gray-50',
    'bg-green-50',
    'bg-indigo-50',
    'bg-primary-50',
    'bg-primary-600',
    'bg-red-50',
    'bg-white',
    'p-3',
    'p-4',
    'p-5',
    'p-6',
    'px-2',
    'px-3',
    'py-0.5',
    'py-1',
    'py-2',
    'text-[11px]',
    'text-2xl',
    'text-3xl',
    'text-base',
    'text-lg',
    'text-sm',
    'text-xs',
    'text-xl',
    'font-bold',
    'font-medium',
    'font-normal',
    'font-semibold',
    'text-amber-800',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-900',
    'text-gray-950',
    'text-green-700',
    'text-green-800',
    'text-indigo-800',
    'text-primary-700',
    'text-red-800',
    'text-white',
    'shadow-sm',
    'transition',
    'hover:bg-primary-500',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'focus:ring-primary-500',
    'sm:grid-cols-3',
    'md:flex-row',
    'md:grid-cols-2',
    'md:items-start',
    'md:justify-between',
    'md:ml-auto',
    'md:self-start',
    'dark:border-gray-600',
    'dark:border-gray-700',
    'dark:border-green-800',
    'dark:border-red-800',
    'dark:bg-gray-700/50',
    'dark:bg-gray-800',
    'dark:bg-green-900/20',
    'dark:bg-primary-900/20',
    'dark:bg-red-900/20',
    'dark:text-gray-400',
    'dark:text-green-300',
    'dark:text-green-400',
    'dark:text-primary-400',
    'dark:text-red-300',
    'dark:text-white',
]

export default {
    presets: [preset],
    safelist: scheduledConferenceBillingHookSafelist,
    theme: {
        extend: {
            fontFamily: {
                sans: [
                    '"Twemoji Country Flags"',
                    'var(--font-family)',
                    ...defaultTheme.fontFamily.sans,
                ],
            },
        },
    },
    content: [
        './app/Administration/**/*.php',
        './app/Filament/**/*.php',
        './app/Livewire/**/*.php',
        './app/Panel/**/*.php',
        './resources/views/components/**/*.blade.php',
        './resources/views/frontend/scheduledConference/pages/**/*.blade.php',
        './resources/views/administration/**/*.blade.php',
        './resources/views/examples/**/*.blade.php',
        './resources/views/filament/**/*.blade.php',
        './resources/views/forms/**/*.blade.php',
        './resources/views/panel/**/*.blade.php',
        './resources/views/vendor/**/*.blade.php',
        './resources/views/infolists/**/*.blade.php',
        './resources/views/forms/**/*.blade.php',
        './resources/views/tables/**/*.blade.php',
        './vendor/awcodes/filament-tiptap-editor/resources/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
    ],
    plugins: [require('tailwindcss-animate')],
}
